version: 2
updates:
  # Ações do GitHub (checkout, setup-python...)
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - chore
    commit-message:
      prefix: chore